# Generated by Django 5.1.7 on 2025-03-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('translit', 'Transliteration'), ('stem', 'Stemming'), ('lemmatize', 'Lemmatization'), ('uzmorphanalyser', 'Morph Analysis'), ('postagging', 'POS Tagging'), ('syllables', 'Syllables'), ('count', 'Count Syllables'), ('genre_classification', 'Genre Classification')], max_length=50, verbose_name='Метод')),
                ('request_text', models.TextField(verbose_name='Текст запроса')),
                ('response_text', models.TextField(verbose_name='Ответ API')),
                ('client_ip', models.GenericIPAddressField(verbose_name='IP клиента')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время запроса')),
            ],
            options={
                'verbose_name': 'Лог API-запроса',
                'verbose_name_plural': 'Логи API-запросов',
            },
        ),
    ]
